### ISSUE TITLE
App crach

### ISSUE THREAD

**Issue by islam2hamy** [MateusRodCosta/Share2Storage#18]
App v. : 1.1.0

FATAL EXCEPTION: main
Process: com.mateusrodcosta.apps.share2storage, PID: 31971
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mateusrodcosta.apps.share2storage/com.mateusrodcosta.apps.share2storage.DetailsActivity}: java.io.IOException: broken file descriptor
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3983)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4136)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:99)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2581)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8720)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: java.io.IOException: broken file descriptor
	at android.graphics.BitmapFactory.nativeDecodeFileDescriptor(Native Method)
	at android.graphics.BitmapFactory.decodeFileDescriptor(BitmapFactory.java:861)
	at android.graphics.BitmapFactory.decodeFileDescriptor(BitmapFactory.java:895)
	at com.mateusrodcosta.apps.share2storage.DetailsActivity.onCreate(Unknown Source:206)
	at android.app.Activity.performCreate(Activity.java:8891)
	at android.app.Activity.performCreate(Activity.java:8856)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1468)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3965)
	... 12 more

**Comment by islam2hamy** [comment]
Yes it is image , from telegram channel

**Comment by MateusRodCosta** [comment]
I added some extra checks to prevent crashing the app if an Exception can happen when trying to decode the image.
It should be available in the next version.

It might also be interesting to add a setting to fully disable previews as well.

**Comment by islam2hamy** [comment]
Thank you
